### ISSUE TITLE
max-width?

### ISSUE THREAD

**Issue by markdaws** [tmont/jquery-dialog#1]
Is there a way to specify a max width the dialog will grow to?  For example if I want to have a dialog with an image in it, I want to dialog to always fill the full width of the screen until the size of the image is exceeded at which point I want the dialog to stop growing in width.  I basically want an easy way to do a full-screen dialog.

**Comment by markdaws** [comment]
I have a few changes that I will submit a pull request for in the next few days.  Sweet library - even if it does use tabs in the code :P  tabs << spaces

**Comment by tmont** [comment]
@markdaws Just lost a lot of respect for you, man. Spaces? Although, it's to be expected coming from an emacs guy...

**Comment by tmont** [comment]
And more relevantly to this issue, the width should grow to fit the content, I think. By default (i.e. the default stylesheet) just sets a min-width and min-height. In fact, even specifying the width/height in the options just sets min-width and min-height (although, now that i think about it, that's probably a bug...).

Go [here](http://tmont.github.io/jquery-dialog/) and run the following in the console:

``` javascript
$.dialog({
    show: true,
    body: $(new Array(15).join('<p>asdlfkajsdlfajsdlfjkasdjlfajsdjfadlsjasdlf jadjsf ladsj fladsj fladsj fladsj lfasd lajsdl fasdkjf ladsj fajsd jfasl fdksfsj las df</p>'))
})
```

You should be able to see that the dialog grows to fits its content (and remains centered in the window).
