### ISSUE TITLE
ability to specify custom header/footer UI

### ISSUE THREAD

**Issue by markdaws** [tmont/jquery-dialog#2]
I want the ability to create a modal that looks like: http://500px.com/photo/42504300?from=popular (click on the image to see the modal view)

**Comment by tmont** [comment]
Currently the header/footer can't really be modified outside of the stylesheet. The footer is purely just for buttons at the moment, and the header just has the title and the close button. There wasn't really meant to be a lot of configurability for those parts. And I'm not entirely sure if I'd want to add that functionality anyway.

You could just make the header and footer part of the body of the dialog, though, and then override the styles to get hide the header and footer completely.

**Comment by markdaws** [comment]
In a fork, I added a header property that allows you to specify a jquery element that will replace the default header, setting it to '' will just hide the existing header.
