### ISSUE TITLE
[Closed - Not Solved] Looking for a Jquery Replacement for onclick="return windowconfirm('Confirm Proceed ?');"

### ISSUE THREAD

**Issue by marcoczen** [tmont/jquery-dialog#3]
Hi,

I currently have a bootstrap form as below;

     <form action="action.php?goto=viewusers" method="post" id="form_viewuser_userlisting">
         // some fields
     </form>

And submit button ( 3 submit buttons actually ,one for add, one for delete, one for edit )

    <button type="submit" class="btn btn-primary" name="button_deluser"  
       onclick="return window.confirm('Delete User ? Confirm Proceed ?');" > Delete Selected User 
    </button>

The above works fine. When the button is clicked, i get a standard javascript popup box which if i select OK, submits the form and the action is done.

Now I would like to get a better looking popup box and hence i have come to your plugin.

How can i use your plugin to replace the standard javascript confirmation box ? Whereby before the form is submitted , a confirmation popup appears and then proceeds only if YES ?

Thanks.

**Comment by marcoczen** [comment]
Bump ?

**Comment by tmont** [comment]
If you're already using Bootstrap, I would just use the Bootstrap modal: http://getbootstrap.com/javascript/#modals

If you want to use this library, all of the logic is handled by you. So set up your buttons with click events, and then pass it to the dialog. Something like this:

```javascript
var $continueBtn = $('<button/>')
  .on('click', function() { /* submit the form here */ })
  .text('Yes');

var $cancelBtn = $('<button/>')
  .attr('data-dialog-action', 'hide')
  .text('No');

var dialog = $.dialog({
  title: 'Are you sure?',
  body: $('<div/>').append($cancelBtn).append($continueBtn)
});

$('<button/>')
  .text('Submit Form')
  .on('click', function() {
    dialog.show();
  })
  .appendTo('body');
```
